### ISSUE TITLE
Image in README.md File Not Showing Properly

### ISSUE THREAD

**Issue by xanthisafk** [xanthisafk/PicRoll#5]
## Issue Description
The image in the `README.md` file is no longer linking properly. When attempting to view the `README.md` file, the image is not displaying correctly.

## Expected Behavior
The README.md file should display the image correctly from the `src/logo` directory.

## Current Behavior
The image in the `README.md` file is not displaying correctly as the files changed recently to a newer logo.

**Comment by GabrielMurry** [comment]
Hey! Just sent a pull request fixing this issue, hope that's ok. Just changed jpg to svg to match the image type.

**Comment by xanthisafk** [comment]
Thanks that fixed it!
